[package]
name = "prompt_get"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.228", features = ["derive"] }
itertools = "0.14.0"
rustc-hash = "2.1.1"

csr_matrix = {path = "src/csr_matrix"}
log = "0.4.28"